using GiftOfTheGivers.Helpers;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace GiftOfTheGivers.Functions;

/// <summary>
/// Generates a dummy donation tax certificate.
///
/// Called by the Gift of the Givers web app after a donor completes the donation form:
///   POST /api/taxcertificate  (JSON body)  -> JSON certificate
///   GET  /api/taxcertificate?reference=GTG-...&amp;amount=500&amp;donor=Thabo  -> simple HTML certificate (browser/Postman friendly)
/// </summary>
public class TaxCertificateFunction
{
    private readonly ILogger<TaxCertificateFunction> _logger;

    public TaxCertificateFunction(ILogger<TaxCertificateFunction> logger)
    {
        _logger = logger;
    }

    [Function("TaxCertificate")]
    public async Task<HttpResponseData> Run(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData request)
    {
        _logger.LogInformation("TaxCertificate function received a {Method} request.", request.Method);

        if (request.Method == "GET")
        {
            return await HandleBrowserRequestAsync(request);
        }

        var certificate = await BuildCertificateFromJsonAsync(request);

        var response = request.CreateResponse(System.Net.HttpStatusCode.OK);
        await response.WriteAsJsonAsync(certificate);

        _logger.LogInformation("Issued tax certificate {CertificateNumber} for donation {Reference}.",
            certificate.CertificateNumber, certificate.DonationReference);

        return response;
    }

    private static async Task<TaxCertificate> BuildCertificateFromJsonAsync(HttpRequestData request)
    {
        TaxCertificateRequest? payload;
        try
        {
            payload = await request.ReadFromJsonAsync<TaxCertificateRequest>();
        }
        catch
        {
            payload = null;
        }

        payload ??= new TaxCertificateRequest();

        return new TaxCertificate
        {
            CertificateNumber = TaxCertificateNumberFormatter.Format(payload.DonationId, payload.CreatedAtUtc),
            DonationReference = payload.Reference,
            DonorName = string.IsNullOrWhiteSpace(payload.DonorName) ? "Anonymous Donor" : payload.DonorName!,
            Amount = payload.Amount,
            Currency = string.IsNullOrWhiteSpace(payload.Currency) ? "ZAR" : payload.Currency,
            DonationType = string.IsNullOrWhiteSpace(payload.DonationType) ? "OneTime" : payload.DonationType,
            IssuedAtUtc = DateTime.UtcNow
        };
    }

    private static async Task<HttpResponseData> HandleBrowserRequestAsync(HttpRequestData request)
    {
        var query = System.Web.HttpUtility.ParseQueryString(request.Url.Query);
        var reference = query["reference"] ?? "GTG-UNKNOWN";
        var donor = string.IsNullOrWhiteSpace(query["donor"]) ? "Anonymous Donor" : query["donor"]!;
        decimal.TryParse(query["amount"], out var amount);
        var currency = string.IsNullOrWhiteSpace(query["currency"]) ? "ZAR" : query["currency"]!;

        var certificate = new TaxCertificate
        {
            CertificateNumber = TaxCertificateNumberFormatter.Format(0, DateTime.UtcNow),
            DonationReference = reference,
            DonorName = donor,
            Amount = amount,
            Currency = currency
        };

        var html = $"""
            <!DOCTYPE html>
            <html>
            <head><title>Donation Tax Certificate</title></head>
            <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 40px auto; padding: 24px; border: 2px solid #2e7d32; border-radius: 8px;">
                <p style="letter-spacing: 3px; color: #2e7d32;"><strong>GIFT OF THE GIVERS</strong></p>
                <h1 style="font-size: 22px;">DONATION TAX CERTIFICATE</h1>
                <p><em>Placeholder certificate generated by the TaxCertificate Azure Function.</em></p>
                <table cellpadding="8">
                    <tr><td><strong>Certificate Number</strong></td><td>{certificate.CertificateNumber}</td></tr>
                    <tr><td><strong>Donation Reference</strong></td><td>{certificate.DonationReference}</td></tr>
                    <tr><td><strong>Donor</strong></td><td>{certificate.DonorName}</td></tr>
                    <tr><td><strong>Amount</strong></td><td>{certificate.FormattedAmount}</td></tr>
                    <tr><td><strong>Issued (UTC)</strong></td><td>{certificate.IssuedAtUtc:dd MMM yyyy HH:mm}</td></tr>
                </table>
                <p style="color: #888; font-size: 12px;">Prototype only - no real tax document is issued.</p>
            </body>
            </html>
            """;

        var response = request.CreateResponse(System.Net.HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/html; charset=utf-8");
        await response.WriteStringAsync(html);

        return response;
    }
}
